module.exports = {
  testEnvironment: 'jsdom',
  roots: ['<rootDir>/tests'],
  testMatch: ['<rootDir>/tests/**/*.test.js', '<rootDir>/tests/**/*.test.ts'],
  transform: {
    '^.+\\.js$': 'babel-jest',
    '^.+\\.ts$': 'ts-jest',
  },
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1',
  },
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  collectCoverageFrom: [
    'background.ts',
    'options.ts',
    'content.ts',
    'utils.ts',
    'themes.ts',
    '!jest.config.cjs',
    '!jest.setup.js',
    '!babel.config.cjs',
    '!**/node_modules/**',
    '!**/coverage/**',
    '!**/*.d.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 75,
      lines: 75,
      statements: 75,
    },
    './background.ts': {
      branches: 60,
      functions: 50,
      lines: 75,
      statements: 75,
    },
    './options.ts': {
      branches: 25,
      functions: 40,
      lines: 45,
      statements: 45,
    },
    './content.ts': {
      branches: 0,
      functions: 0,
      lines: 0,
      statements: 0,
    },
    './utils.ts': {
      branches: 0,
      functions: 15,
      lines: 10,
      statements: 10,
    },
  },
  coverageReporters: ['text', 'lcov', 'html', 'json'],
  testTimeout: 10000,
  verbose: true,
  forceExit: true,
  detectOpenHandles: true,
};
